sudo: false

language: perl
perl:
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - ES_VERSION=1.3.1   ES_OPT=-d TEST_LIVE=1
  - ES_VERSION=1.4.5   ES_OPT=-d TEST_LIVE=1
  - ES_VERSION=1.5.2   ES_OPT=-d TEST_LIVE=1

before_install:
  - curl --silent -L https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar -xz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch $ES_OPT
  - cpanm -n Minilla Devel::Cover::Report::Coveralls
  - curl http://localhost:9200/

script:
  minil build && perl ./Build.PL && ./Build build && cover -test -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

git:
  depth: 1
