language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - ES_VERSION=0.90.0
  - ES_VERSION=0.90.11

before_install:
  - sh t/prepare-travis-ci.sh
  - cpanm -n Minilla Devel::Cover::Report::Coveralls
  - export TEST_LIVE=1

script:
  minil build && perl ./Build.PL && ./Build build && cover -test -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
