language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  cpanm -n Minilla
script:
  minil test

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

