language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - TEST_LIVE=1 ES_VERSION=0.90.0  ES_OPT=
  - TEST_LIVE=1 ES_VERSION=0.90.11 ES_OPT=
  - TEST_LIVE=1 ES_VERSION=1.1.1   ES_OPT=-d

before_install:
  - curl --silent -L http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar -xz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch $ES_OPT
  - cpanm -n Minilla Devel::Cover::Report::Coveralls
  - curl http://localhost:9200/

script:
  minil build && perl ./Build.PL && ./Build build && cover -test -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
